type AccountMessage = { kind: "verification" | "reset" | "welcome"; nombre: string; otp?: string; publicUrl?: string };
const escape = (value: string) => value.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);

/** Table layout and inline styles work without images, tracking, JS or web fonts. */
export function renderAccountEmail(message: AccountMessage) {
  const name = message.nombre.trim() || "amigo";
  const firstName = name.split(/\s+/)[0];
  const welcome = message.kind === "welcome";
  if (!welcome && !/^\d{6}$/.test(message.otp || "")) throw new Error("Invalid account email code");
  const title = welcome ? "Tu cuenta está lista" : message.kind === "reset" ? "Recupera tu acceso" : "Un paso y estamos juntos";
  const description = welcome ? "Crea tu primer grupo o divide la cuenta de hoy. Tú registras los gastos; JUNTO hace las cuentas." : message.kind === "reset" ? "Usa este código en JUNTO para cambiar tu contraseña." : "Escribe este código en JUNTO para verificar que este correo es tuyo.";
  let href = "";
  try { const url = new URL(message.publicUrl || ""); if (url.protocol === "https:" && !url.username && !url.password) href = url.href; } catch { /* No misleading link when the public website is not configured. */ }
  const code = welcome ? "" : `<table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="background:#E5FAF3;border:1px solid #B9EBDD;border-radius:16px;padding:22px 12px;color:#082644;font-size:34px;letter-spacing:8px;font-weight:800;font-family:Arial,sans-serif">${message.otp}</td></tr></table><p style="font-size:14px;color:#64748B;line-height:1.6;margin:16px 0 0">Válido durante 15 minutos. No compartas este código con nadie. JUNTO nunca te lo pedirá por WhatsApp ni por teléfono.</p>`;
  const steps = welcome ? `<table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="background:#F2EDFF;border-radius:16px;padding:20px;font-size:15px;color:#082644;line-height:1.8"><b>1.</b> Crea un grupo o una cuenta puntual.<br><b>2.</b> Anota quién pagó y para quién fue.<br><b>3.</b> Revisa quién debe a quién y confirma los pagos recibidos.</td></tr></table>${href ? `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:24px"><tr><td align="center" bgcolor="#00856A" style="border-radius:14px"><a href="${escape(href)}" style="display:block;padding:16px;color:#FFFFFF;font-weight:700;text-decoration:none;font-size:16px">Abrir JUNTO →</a></td></tr></table>` : ""}` : code;
  return {
    subject: welcome ? `¡Bienvenido a JUNTO, ${firstName}!` : message.kind === "reset" ? "Tu código para recuperar el acceso · JUNTO" : "Verifica tu correo · JUNTO",
    text: `Hola ${name}. ${title}. ${description}${welcome ? "" : ` Tu código es ${message.otp}. Expira en 15 minutos. No lo compartas con nadie. Si no lo solicitaste, ignora este mensaje.`}\n\nJUNTO registra y divide gastos; no guarda ni transfiere dinero.`,
    html: `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · JUNTO</title></head><body style="margin:0;padding:0;background:#FFFCF7;font-family:Arial,sans-serif;color:#082644"><span style="display:none;max-height:0;overflow:hidden">${description}</span><table role="presentation" width="100%" cellspacing="0" cellpadding="0" bgcolor="#FFFCF7"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:540px;background:#FFFFFF;border:1px solid #E6EAF0;border-radius:22px"><tr><td style="padding:28px 24px;background:#E5FAF3;border-radius:22px 22px 0 0"><p style="margin:0;font-size:30px;font-weight:800;color:#00856A;letter-spacing:-1px">JUNTO</p><p style="margin:6px 0 0;font-size:14px;color:#456579">Las cuentas claras. Los buenos momentos, juntos.</p></td></tr><tr><td style="padding:28px 24px"><p style="margin:0 0 10px;font-size:15px;color:#64748B">Hola, ${escape(name)} 👋</p><h1 style="margin:0 0 14px;font-size:26px;line-height:1.3;color:#082644">${title}</h1><p style="font-size:16px;line-height:1.7;margin:0 0 24px">${description}</p>${steps}${welcome ? "" : '<p style="font-size:14px;line-height:1.6;color:#64748B;margin:22px 0 0">¿No lo solicitaste? Puedes ignorar este correo. No se cambiará tu cuenta por recibir este mensaje.</p>'}</td></tr><tr><td style="padding:20px 24px;border-top:1px solid #E6EAF0;font-size:12px;line-height:1.6;color:#64748B">JUNTO no guarda ni transfiere dinero. Los pagos se realizan por fuera y se registran cuando corresponda.</td></tr></table></td></tr></table></body></html>`,
  };
}
